allowBuilds:
  es5-ext: true
  msw: true
  sharp: true
  unrs-resolver: true
overrides:
  hono@<4.12.25: ">=4.12.25"
  postcss@<8.5.18: ">=8.5.18"
  qs@>=6.11.1 <=6.15.1: ">=6.15.2"
  js-yaml@>=4.0.0 <=4.1.1: ">=4.1.2"
  "@babel/core@<=7.29.0": ">=7.29.1"
  "@hono/node-server@<2.0.10": ">=2.0.10"
  "sharp@<0.35.0": ">=0.35.0"
